In [1]:
import pandas as pd
import numpy as np

In [6]:
oxi_gene = pd.read_excel("/home/chit/Desktop/Thesis/data/4timepoints/GeneListed_Oxi_Repair.xlsx")
oxi_gene[['ID']]

        ID
0   DHCR24
1    BNIP3
2     CCL5
3    MPV17
4     NQO1
..     ...
65  TXNRD2
66     TXN
67     TPO
68     TTN
69    UCP2

[70 rows x 1 columns]

In [53]:
clusters = pd.read_csv("/home/chit/Desktop/Thesis/results/05.08/cluster_table.csv")
filter1 = clusters[clusters['object'].isin(oxi_gene['ID'])].cluster.unique()

In [31]:
with open("/home/chit/Desktop/Thesis/results/05.08/all_connect.txt") as f:
    connect = f.read().split("\n")

<generator object <genexpr> at 0x7f6c022481b0>

In [50]:
logodd_cluster = []
for a in connect:
    split = a.split("_")
    for b in split:
        c = "Cluster "+ b
        if c not in logodd_cluster:
            logodd_cluster.append(c)

In [64]:
##filter the clusters and oxi gene list
highlogodd = clusters[clusters['cluster'].isin(logodd_cluster)]
gene_list = highlogodd[highlogodd['object'].isin(oxi_gene['ID'])].object

In [66]:
##bg list = clusters in highlogodd
bg = highlogodd.object

8819        HMCES
8820        TMED1
8821       NDUFS7
8822       MINOS1
8823       ZCCHC4
           ...
19815      HECTD2
19816      STK32B
19817       RWDD1
19818     DNAJB12
19819    ATP6V0A2
Name: object, Length: 6592, dtype: object